# Generated by Django 5.0.3 on 2024-04-03 13:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triviabyte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
