# Generated by Django 5.0.3 on 2024-04-04 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triviabyte', '0002_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.DeleteModel(
            name='QuizApp',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuizCategory',
        ),
    ]
