# Generated by Django 5.0.3 on 2024-04-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('triviabyte', '0003_remove_answer_question_remove_question_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('question_text', models.TextField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('answer_choices', models.TextField()),
            ],
        ),
    ]
